.ifdef __24F04KA200
.include "p24F04KA200.inc"
.equ VALID_ID,1
.endif

.ifdef __24F04KA201
.include "p24F04KA201.inc"
.equ VALID_ID,1
.endif

.ifdef __24F04KL100
.include "p24F04KL100.inc"
.equ VALID_ID,1
.endif

.ifdef __24F04KL101
.include "p24F04KL101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KA101
.include "p24F08KA101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KA102
.include "p24F08KA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL200
.include "p24F08KL200.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL201
.include "p24F08KL201.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL301
.include "p24F08KL301.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL302
.include "p24F08KL302.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL401
.include "p24F08KL401.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL402
.include "p24F08KL402.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM101
.include "p24F08KM101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM102
.include "p24F08KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM202
.include "p24F08KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM204
.include "p24F08KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA101
.include "p24F16KA101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA102
.include "p24F16KA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA301
.include "p24F16KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA302
.include "p24F16KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA304
.include "p24F16KA304.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KL401
.include "p24F16KL401.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KL402
.include "p24F16KL402.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM102
.include "p24F16KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM104
.include "p24F16KM104.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM202
.include "p24F16KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM204
.include "p24F16KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24F32KA301
.include "p24F32KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24F32KA302
.include "p24F32KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24F32KA304
.include "p24F32KA304.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA106
.include "p24FJ128DA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA110
.include "p24FJ128DA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA206
.include "p24FJ128DA206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA210
.include "p24FJ128DA210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA006
.include "p24FJ128GA006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA008
.include "p24FJ128GA008.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA010
.include "p24FJ128GA010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA106
.include "p24FJ128GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA108
.include "p24FJ128GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA110
.include "p24FJ128GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA202
.include "p24FJ128GA202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA204
.include "p24FJ128GA204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA306
.include "p24FJ128GA306.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA308
.include "p24FJ128GA308.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA310
.include "p24FJ128GA310.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB106
.include "p24FJ128GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB108
.include "p24FJ128GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB110
.include "p24FJ128GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB202
.include "p24FJ128GB202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB204
.include "p24FJ128GB204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB206
.include "p24FJ128GB206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB210
.include "p24FJ128GB210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GC006
.include "p24FJ128GC006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GC010
.include "p24FJ128GC010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16GA002
.include "p24FJ16GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16GA004
.include "p24FJ16GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16MC101
.include "p24FJ16MC101.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16MC102
.include "p24FJ16MC102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GA106
.include "p24FJ192GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GA108
.include "p24FJ192GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GA110
.include "p24FJ192GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GB106
.include "p24FJ192GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GB108
.include "p24FJ192GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GB110
.include "p24FJ192GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA106
.include "p24FJ256DA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA110
.include "p24FJ256DA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA206
.include "p24FJ256DA206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA210
.include "p24FJ256DA210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GA106
.include "p24FJ256GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GA108
.include "p24FJ256GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GA110
.include "p24FJ256GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB106
.include "p24FJ256GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB108
.include "p24FJ256GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB110
.include "p24FJ256GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB206
.include "p24FJ256GB206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB210
.include "p24FJ256GB210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA002
.include "p24FJ32GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA004
.include "p24FJ32GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA102
.include "p24FJ32GA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA104
.include "p24FJ32GA104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GB002
.include "p24FJ32GB002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GB004
.include "p24FJ32GB004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32MC101
.include "p24FJ32MC101.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32MC102
.include "p24FJ32MC102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32MC104
.include "p24FJ32MC104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ48GA002
.include "p24FJ48GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ48GA004
.include "p24FJ48GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA002
.include "p24FJ64GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA004
.include "p24FJ64GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA006
.include "p24FJ64GA006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA008
.include "p24FJ64GA008.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA010
.include "p24FJ64GA010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA102
.include "p24FJ64GA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA104
.include "p24FJ64GA104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA106
.include "p24FJ64GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA108
.include "p24FJ64GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA110
.include "p24FJ64GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA202
.include "p24FJ64GA202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA204
.include "p24FJ64GA204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA306
.include "p24FJ64GA306.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA308
.include "p24FJ64GA308.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA310
.include "p24FJ64GA310.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB002
.include "p24FJ64GB002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB004
.include "p24FJ64GB004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB106
.include "p24FJ64GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB108
.include "p24FJ64GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB110
.include "p24FJ64GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB202
.include "p24FJ64GB202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB204
.include "p24FJ64GB204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GC006
.include "p24FJ64GC006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GC010
.include "p24FJ64GC010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ96GA006
.include "p24FJ96GA006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ96GA008
.include "p24FJ96GA008.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ96GA010
.include "p24FJ96GA010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM101
.include "p24FV08KM101.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM102
.include "p24FV08KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM202
.include "p24FV08KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM204
.include "p24FV08KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KA301
.include "p24FV16KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KA302
.include "p24FV16KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KA304
.include "p24FV16KA304.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM102
.include "p24FV16KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM104
.include "p24FV16KM104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM202
.include "p24FV16KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM204
.include "p24FV16KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV32KA301
.include "p24FV32KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV32KA302
.include "p24FV32KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV32KA304
.include "p24FV32KA304.inc"
.equ VALID_ID,1
.endif

.ifndef VALID_ID
.error "processor ID not specified in generic include file"
.endif
