.ifdef __33EP128GM304
.include "p33EP128GM304.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM306
.include "p33EP128GM306.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM310
.include "p33EP128GM310.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM604
.include "p33EP128GM604.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM706
.include "p33EP128GM706.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM710
.include "p33EP128GM710.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GP502
.include "p33EP128GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GP504
.include "p33EP128GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GP506
.include "p33EP128GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC202
.include "p33EP128MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC204
.include "p33EP128MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC206
.include "p33EP128MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC502
.include "p33EP128MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC504
.include "p33EP128MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC506
.include "p33EP128MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU202
.include "p33EP128MU202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU204
.include "p33EP128MU204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU206
.include "p33EP128MU206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU502
.include "p33EP128MU502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU504
.include "p33EP128MU504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU506
.include "p33EP128MU506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP16GS502
.include "p33EP16GS502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP16GS504
.include "p33EP16GS504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP16GS506
.include "p33EP16GS506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM304
.include "p33EP256GM304.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM306
.include "p33EP256GM306.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM310
.include "p33EP256GM310.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM604
.include "p33EP256GM604.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM706
.include "p33EP256GM706.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM710
.include "p33EP256GM710.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GP502
.include "p33EP256GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GP504
.include "p33EP256GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GP506
.include "p33EP256GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC202
.include "p33EP256MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC204
.include "p33EP256MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC206
.include "p33EP256MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC502
.include "p33EP256MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC504
.include "p33EP256MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC506
.include "p33EP256MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU202
.include "p33EP256MU202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU204
.include "p33EP256MU204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU206
.include "p33EP256MU206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU502
.include "p33EP256MU502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU504
.include "p33EP256MU504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU506
.include "p33EP256MU506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU806
.include "p33EP256MU806.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU810
.include "p33EP256MU810.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU814
.include "p33EP256MU814.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GP502
.include "p33EP32GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GP503
.include "p33EP32GP503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GP504
.include "p33EP32GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS202
.include "p33EP32GS202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS502
.include "p33EP32GS502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS504
.include "p33EP32GS504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS506
.include "p33EP32GS506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC202
.include "p33EP32MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC203
.include "p33EP32MC203.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC204
.include "p33EP32MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC502
.include "p33EP32MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC503
.include "p33EP32MC503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC504
.include "p33EP32MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM304
.include "p33EP512GM304.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM306
.include "p33EP512GM306.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM310
.include "p33EP512GM310.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM604
.include "p33EP512GM604.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM706
.include "p33EP512GM706.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM710
.include "p33EP512GM710.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP502
.include "p33EP512GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP504
.include "p33EP512GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP506
.include "p33EP512GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP806
.include "p33EP512GP806.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC202
.include "p33EP512MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC204
.include "p33EP512MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC206
.include "p33EP512MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC502
.include "p33EP512MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC504
.include "p33EP512MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC506
.include "p33EP512MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC806
.include "p33EP512MC806.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MU810
.include "p33EP512MU810.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MU814
.include "p33EP512MU814.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP502
.include "p33EP64GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP503
.include "p33EP64GP503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP504
.include "p33EP64GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP506
.include "p33EP64GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GS502
.include "p33EP64GS502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GS504
.include "p33EP64GS504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GS506
.include "p33EP64GS506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC202
.include "p33EP64MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC203
.include "p33EP64MC203.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC204
.include "p33EP64MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC206
.include "p33EP64MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC502
.include "p33EP64MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC503
.include "p33EP64MC503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC504
.include "p33EP64MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC506
.include "p33EP64MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU202
.include "p33EP64MU202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU204
.include "p33EP64MU204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU206
.include "p33EP64MU206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU502
.include "p33EP64MU502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU504
.include "p33EP64MU504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU506
.include "p33EP64MU506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM002
.include "p33EV128GM002.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM004
.include "p33EV128GM004.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM006
.include "p33EV128GM006.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM102
.include "p33EV128GM102.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM104
.include "p33EV128GM104.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM106
.include "p33EV128GM106.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM002
.include "p33EV256GM002.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM004
.include "p33EV256GM004.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM006
.include "p33EV256GM006.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM102
.include "p33EV256GM102.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM104
.include "p33EV256GM104.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM106
.include "p33EV256GM106.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM002
.include "p33EV64GM002.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM004
.include "p33EV64GM004.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM006
.include "p33EV64GM006.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM102
.include "p33EV64GM102.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM104
.include "p33EV64GM104.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM106
.include "p33EV64GM106.inc"
.equ VALID_ID,1
.endif

.ifndef VALID_ID
.error "processor ID not specified in generic include file"
.endif
