;
;  xc.inc 
;
;  Generic include file for XC16
;
;  Copyright 2012 Microchip Technology
;

.ifdef __24EP128GP202
.include "p24EP128GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP128GP204
.include "p24EP128GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP128GP206
.include "p24EP128GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP128MC202
.include "p24EP128MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP128MC204
.include "p24EP128MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP128MC206
.include "p24EP128MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256GP202
.include "p24EP256GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256GP204
.include "p24EP256GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256GP206
.include "p24EP256GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256GU810
.include "p24EP256GU810.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256GU814
.include "p24EP256GU814.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256MC202
.include "p24EP256MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256MC204
.include "p24EP256MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP256MC206
.include "p24EP256MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP32GP202
.include "p24EP32GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP32GP203
.include "p24EP32GP203.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP32GP204
.include "p24EP32GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP32MC202
.include "p24EP32MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP32MC203
.include "p24EP32MC203.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP32MC204
.include "p24EP32MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512GP202
.include "p24EP512GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512GP204
.include "p24EP512GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512GP206
.include "p24EP512GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512GP806
.include "p24EP512GP806.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512GU810
.include "p24EP512GU810.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512GU814
.include "p24EP512GU814.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512MC202
.include "p24EP512MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512MC204
.include "p24EP512MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP512MC206
.include "p24EP512MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64GP202
.include "p24EP64GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64GP203
.include "p24EP64GP203.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64GP204
.include "p24EP64GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64GP206
.include "p24EP64GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64MC202
.include "p24EP64MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64MC203
.include "p24EP64MC203.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64MC204
.include "p24EP64MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __24EP64MC206
.include "p24EP64MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __24F04KA200
.include "p24F04KA200.inc"
.equ VALID_ID,1
.endif

.ifdef __24F04KA201
.include "p24F04KA201.inc"
.equ VALID_ID,1
.endif

.ifdef __24F04KL100
.include "p24F04KL100.inc"
.equ VALID_ID,1
.endif

.ifdef __24F04KL101
.include "p24F04KL101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KA101
.include "p24F08KA101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KA102
.include "p24F08KA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL200
.include "p24F08KL200.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL201
.include "p24F08KL201.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL301
.include "p24F08KL301.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL302
.include "p24F08KL302.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL401
.include "p24F08KL401.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KL402
.include "p24F08KL402.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM101
.include "p24F08KM101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM102
.include "p24F08KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM202
.include "p24F08KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24F08KM204
.include "p24F08KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA101
.include "p24F16KA101.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA102
.include "p24F16KA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA301
.include "p24F16KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA302
.include "p24F16KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KA304
.include "p24F16KA304.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KL401
.include "p24F16KL401.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KL402
.include "p24F16KL402.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM102
.include "p24F16KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM104
.include "p24F16KM104.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM202
.include "p24F16KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24F16KM204
.include "p24F16KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24F32KA301
.include "p24F32KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24F32KA302
.include "p24F32KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24F32KA304
.include "p24F32KA304.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA106
.include "p24FJ128DA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA110
.include "p24FJ128DA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA206
.include "p24FJ128DA206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128DA210
.include "p24FJ128DA210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA006
.include "p24FJ128GA006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA008
.include "p24FJ128GA008.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA010
.include "p24FJ128GA010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA106
.include "p24FJ128GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA108
.include "p24FJ128GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA110
.include "p24FJ128GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA202
.include "p24FJ128GA202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA204
.include "p24FJ128GA204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA306
.include "p24FJ128GA306.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA308
.include "p24FJ128GA308.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GA310
.include "p24FJ128GA310.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB106
.include "p24FJ128GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB108
.include "p24FJ128GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB110
.include "p24FJ128GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB202
.include "p24FJ128GB202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB204
.include "p24FJ128GB204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB206
.include "p24FJ128GB206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GB210
.include "p24FJ128GB210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GC006
.include "p24FJ128GC006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ128GC010
.include "p24FJ128GC010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16GA002
.include "p24FJ16GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16GA004
.include "p24FJ16GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16MC101
.include "p24FJ16MC101.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ16MC102
.include "p24FJ16MC102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GA106
.include "p24FJ192GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GA108
.include "p24FJ192GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GA110
.include "p24FJ192GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GB106
.include "p24FJ192GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GB108
.include "p24FJ192GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ192GB110
.include "p24FJ192GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA106
.include "p24FJ256DA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA110
.include "p24FJ256DA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA206
.include "p24FJ256DA206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256DA210
.include "p24FJ256DA210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GA106
.include "p24FJ256GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GA108
.include "p24FJ256GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GA110
.include "p24FJ256GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB106
.include "p24FJ256GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB108
.include "p24FJ256GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB110
.include "p24FJ256GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB206
.include "p24FJ256GB206.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ256GB210
.include "p24FJ256GB210.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA002
.include "p24FJ32GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA004
.include "p24FJ32GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA102
.include "p24FJ32GA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GA104
.include "p24FJ32GA104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GB002
.include "p24FJ32GB002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32GB004
.include "p24FJ32GB004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32MC101
.include "p24FJ32MC101.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32MC102
.include "p24FJ32MC102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ32MC104
.include "p24FJ32MC104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ48GA002
.include "p24FJ48GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ48GA004
.include "p24FJ48GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA002
.include "p24FJ64GA002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA004
.include "p24FJ64GA004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA006
.include "p24FJ64GA006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA008
.include "p24FJ64GA008.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA010
.include "p24FJ64GA010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA102
.include "p24FJ64GA102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA104
.include "p24FJ64GA104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA106
.include "p24FJ64GA106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA108
.include "p24FJ64GA108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA110
.include "p24FJ64GA110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA202
.include "p24FJ64GA202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA204
.include "p24FJ64GA204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA306
.include "p24FJ64GA306.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA308
.include "p24FJ64GA308.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GA310
.include "p24FJ64GA310.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB002
.include "p24FJ64GB002.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB004
.include "p24FJ64GB004.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB106
.include "p24FJ64GB106.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB108
.include "p24FJ64GB108.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB110
.include "p24FJ64GB110.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB202
.include "p24FJ64GB202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GB204
.include "p24FJ64GB204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GC006
.include "p24FJ64GC006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ64GC010
.include "p24FJ64GC010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ96GA006
.include "p24FJ96GA006.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ96GA008
.include "p24FJ96GA008.inc"
.equ VALID_ID,1
.endif

.ifdef __24FJ96GA010
.include "p24FJ96GA010.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM101
.include "p24FV08KM101.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM102
.include "p24FV08KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM202
.include "p24FV08KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV08KM204
.include "p24FV08KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KA301
.include "p24FV16KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KA302
.include "p24FV16KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KA304
.include "p24FV16KA304.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM102
.include "p24FV16KM102.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM104
.include "p24FV16KM104.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM202
.include "p24FV16KM202.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV16KM204
.include "p24FV16KM204.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV32KA301
.include "p24FV32KA301.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV32KA302
.include "p24FV32KA302.inc"
.equ VALID_ID,1
.endif

.ifdef __24FV32KA304
.include "p24FV32KA304.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP202
.include "p24HJ128GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP204
.include "p24HJ128GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP206
.include "p24HJ128GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP206A
.include "p24HJ128GP206A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP210
.include "p24HJ128GP210.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP210A
.include "p24HJ128GP210A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP306
.include "p24HJ128GP306.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP306A
.include "p24HJ128GP306A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP310
.include "p24HJ128GP310.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP310A
.include "p24HJ128GP310A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP502
.include "p24HJ128GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP504
.include "p24HJ128GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP506
.include "p24HJ128GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP506A
.include "p24HJ128GP506A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP510
.include "p24HJ128GP510.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ128GP510A
.include "p24HJ128GP510A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ12GP201
.include "p24HJ12GP201.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ12GP202
.include "p24HJ12GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ16GP304
.include "p24HJ16GP304.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ256GP206
.include "p24HJ256GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ256GP206A
.include "p24HJ256GP206A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ256GP210
.include "p24HJ256GP210.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ256GP210A
.include "p24HJ256GP210A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ256GP610
.include "p24HJ256GP610.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ256GP610A
.include "p24HJ256GP610A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ32GP202
.include "p24HJ32GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ32GP204
.include "p24HJ32GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ32GP302
.include "p24HJ32GP302.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ32GP304
.include "p24HJ32GP304.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP202
.include "p24HJ64GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP204
.include "p24HJ64GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP206
.include "p24HJ64GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP206A
.include "p24HJ64GP206A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP210
.include "p24HJ64GP210.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP210A
.include "p24HJ64GP210A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP502
.include "p24HJ64GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP504
.include "p24HJ64GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP506
.include "p24HJ64GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP506A
.include "p24HJ64GP506A.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP510
.include "p24HJ64GP510.inc"
.equ VALID_ID,1
.endif

.ifdef __24HJ64GP510A
.include "p24HJ64GP510A.inc"
.equ VALID_ID,1
.endif

.ifdef __30F1010
.include "p30F1010.inc"
.equ VALID_ID,1
.endif

.ifdef __30F2010
.include "p30F2010.inc"
.equ VALID_ID,1
.endif

.ifdef __30F2011
.include "p30F2011.inc"
.equ VALID_ID,1
.endif

.ifdef __30F2012
.include "p30F2012.inc"
.equ VALID_ID,1
.endif

.ifdef __30F2020
.include "p30F2020.inc"
.equ VALID_ID,1
.endif

.ifdef __30F2023
.include "p30F2023.inc"
.equ VALID_ID,1
.endif

.ifdef __30F3010
.include "p30F3010.inc"
.equ VALID_ID,1
.endif

.ifdef __30F3011
.include "p30F3011.inc"
.equ VALID_ID,1
.endif

.ifdef __30F3012
.include "p30F3012.inc"
.equ VALID_ID,1
.endif

.ifdef __30F3013
.include "p30F3013.inc"
.equ VALID_ID,1
.endif

.ifdef __30F3014
.include "p30F3014.inc"
.equ VALID_ID,1
.endif

.ifdef __30F4011
.include "p30F4011.inc"
.equ VALID_ID,1
.endif

.ifdef __30F4012
.include "p30F4012.inc"
.equ VALID_ID,1
.endif

.ifdef __30F4013
.include "p30F4013.inc"
.equ VALID_ID,1
.endif

.ifdef __30F5011
.include "p30F5011.inc"
.equ VALID_ID,1
.endif

.ifdef __30F5013
.include "p30F5013.inc"
.equ VALID_ID,1
.endif

.ifdef __30F5015
.include "p30F5015.inc"
.equ VALID_ID,1
.endif

.ifdef __30F5016
.include "p30F5016.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6010
.include "p30F6010.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6010A
.include "p30F6010A.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6011
.include "p30F6011.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6011A
.include "p30F6011A.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6012
.include "p30F6012.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6012A
.include "p30F6012A.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6013
.include "p30F6013.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6013A
.include "p30F6013A.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6014
.include "p30F6014.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6014A
.include "p30F6014A.inc"
.equ VALID_ID,1
.endif

.ifdef __30F6015
.include "p30F6015.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM304
.include "p33EP128GM304.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM306
.include "p33EP128GM306.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM310
.include "p33EP128GM310.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM604
.include "p33EP128GM604.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM706
.include "p33EP128GM706.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GM710
.include "p33EP128GM710.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GP502
.include "p33EP128GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GP504
.include "p33EP128GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128GP506
.include "p33EP128GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC202
.include "p33EP128MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC204
.include "p33EP128MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC206
.include "p33EP128MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC502
.include "p33EP128MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC504
.include "p33EP128MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MC506
.include "p33EP128MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU202
.include "p33EP128MU202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU204
.include "p33EP128MU204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU206
.include "p33EP128MU206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU502
.include "p33EP128MU502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU504
.include "p33EP128MU504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP128MU506
.include "p33EP128MU506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP16GS502
.include "p33EP16GS502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP16GS504
.include "p33EP16GS504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP16GS506
.include "p33EP16GS506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM304
.include "p33EP256GM304.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM306
.include "p33EP256GM306.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM310
.include "p33EP256GM310.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM604
.include "p33EP256GM604.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM706
.include "p33EP256GM706.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GM710
.include "p33EP256GM710.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GP502
.include "p33EP256GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GP504
.include "p33EP256GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256GP506
.include "p33EP256GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC202
.include "p33EP256MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC204
.include "p33EP256MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC206
.include "p33EP256MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC502
.include "p33EP256MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC504
.include "p33EP256MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MC506
.include "p33EP256MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU202
.include "p33EP256MU202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU204
.include "p33EP256MU204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU206
.include "p33EP256MU206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU502
.include "p33EP256MU502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU504
.include "p33EP256MU504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU506
.include "p33EP256MU506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU806
.include "p33EP256MU806.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU810
.include "p33EP256MU810.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP256MU814
.include "p33EP256MU814.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GP502
.include "p33EP32GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GP503
.include "p33EP32GP503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GP504
.include "p33EP32GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS202
.include "p33EP32GS202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS502
.include "p33EP32GS502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS504
.include "p33EP32GS504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32GS506
.include "p33EP32GS506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC202
.include "p33EP32MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC203
.include "p33EP32MC203.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC204
.include "p33EP32MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC502
.include "p33EP32MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC503
.include "p33EP32MC503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP32MC504
.include "p33EP32MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM304
.include "p33EP512GM304.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM306
.include "p33EP512GM306.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM310
.include "p33EP512GM310.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM604
.include "p33EP512GM604.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM706
.include "p33EP512GM706.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GM710
.include "p33EP512GM710.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP502
.include "p33EP512GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP504
.include "p33EP512GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP506
.include "p33EP512GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512GP806
.include "p33EP512GP806.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC202
.include "p33EP512MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC204
.include "p33EP512MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC206
.include "p33EP512MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC502
.include "p33EP512MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC504
.include "p33EP512MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC506
.include "p33EP512MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MC806
.include "p33EP512MC806.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MU810
.include "p33EP512MU810.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP512MU814
.include "p33EP512MU814.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP502
.include "p33EP64GP502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP503
.include "p33EP64GP503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP504
.include "p33EP64GP504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GP506
.include "p33EP64GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GS502
.include "p33EP64GS502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GS504
.include "p33EP64GS504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64GS506
.include "p33EP64GS506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC202
.include "p33EP64MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC203
.include "p33EP64MC203.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC204
.include "p33EP64MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC206
.include "p33EP64MC206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC502
.include "p33EP64MC502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC503
.include "p33EP64MC503.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC504
.include "p33EP64MC504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MC506
.include "p33EP64MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU202
.include "p33EP64MU202.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU204
.include "p33EP64MU204.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU206
.include "p33EP64MU206.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU502
.include "p33EP64MU502.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU504
.include "p33EP64MU504.inc"
.equ VALID_ID,1
.endif

.ifdef __33EP64MU506
.include "p33EP64MU506.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM002
.include "p33EV128GM002.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM004
.include "p33EV128GM004.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM006
.include "p33EV128GM006.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM102
.include "p33EV128GM102.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM104
.include "p33EV128GM104.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV128GM106
.include "p33EV128GM106.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM002
.include "p33EV256GM002.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM004
.include "p33EV256GM004.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM006
.include "p33EV256GM006.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM102
.include "p33EV256GM102.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM104
.include "p33EV256GM104.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV256GM106
.include "p33EV256GM106.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM002
.include "p33EV64GM002.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM004
.include "p33EV64GM004.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM006
.include "p33EV64GM006.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM102
.include "p33EV64GM102.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM104
.include "p33EV64GM104.inc"
.equ VALID_ID,1
.endif

.ifdef __33EV64GM106
.include "p33EV64GM106.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ06GS001
.include "p33FJ06GS001.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ06GS101
.include "p33FJ06GS101.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ06GS101A
.include "p33FJ06GS101A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ06GS102
.include "p33FJ06GS102.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ06GS102A
.include "p33FJ06GS102A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ06GS202
.include "p33FJ06GS202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ06GS202A
.include "p33FJ06GS202A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ09GS302
.include "p33FJ09GS302.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP202
.include "p33FJ128GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP204
.include "p33FJ128GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP206
.include "p33FJ128GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP206A
.include "p33FJ128GP206A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP306
.include "p33FJ128GP306.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP306A
.include "p33FJ128GP306A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP310
.include "p33FJ128GP310.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP310A
.include "p33FJ128GP310A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP706
.include "p33FJ128GP706.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP706A
.include "p33FJ128GP706A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP708
.include "p33FJ128GP708.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP708A
.include "p33FJ128GP708A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP710
.include "p33FJ128GP710.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP710A
.include "p33FJ128GP710A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP802
.include "p33FJ128GP802.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128GP804
.include "p33FJ128GP804.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC202
.include "p33FJ128MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC204
.include "p33FJ128MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC506
.include "p33FJ128MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC506A
.include "p33FJ128MC506A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC510
.include "p33FJ128MC510.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC510A
.include "p33FJ128MC510A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC706
.include "p33FJ128MC706.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC706A
.include "p33FJ128MC706A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC708
.include "p33FJ128MC708.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC708A
.include "p33FJ128MC708A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC710
.include "p33FJ128MC710.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC710A
.include "p33FJ128MC710A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC802
.include "p33FJ128MC802.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ128MC804
.include "p33FJ128MC804.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ12GP201
.include "p33FJ12GP201.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ12GP202
.include "p33FJ12GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ12MC201
.include "p33FJ12MC201.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ12MC202
.include "p33FJ12MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16GP101
.include "p33FJ16GP101.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16GP102
.include "p33FJ16GP102.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16GP304
.include "p33FJ16GP304.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16GS402
.include "p33FJ16GS402.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16GS404
.include "p33FJ16GS404.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16GS502
.include "p33FJ16GS502.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16GS504
.include "p33FJ16GS504.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16MC101
.include "p33FJ16MC101.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16MC102
.include "p33FJ16MC102.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ16MC304
.include "p33FJ16MC304.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256GP506
.include "p33FJ256GP506.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256GP506A
.include "p33FJ256GP506A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256GP510
.include "p33FJ256GP510.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256GP510A
.include "p33FJ256GP510A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256GP710
.include "p33FJ256GP710.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256GP710A
.include "p33FJ256GP710A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256MC510
.include "p33FJ256MC510.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256MC510A
.include "p33FJ256MC510A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256MC710
.include "p33FJ256MC710.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ256MC710A
.include "p33FJ256MC710A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GP101
.include "p33FJ32GP101.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GP102
.include "p33FJ32GP102.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GP104
.include "p33FJ32GP104.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GP202
.include "p33FJ32GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GP204
.include "p33FJ32GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GP302
.include "p33FJ32GP302.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GP304
.include "p33FJ32GP304.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GS406
.include "p33FJ32GS406.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GS606
.include "p33FJ32GS606.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GS608
.include "p33FJ32GS608.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32GS610
.include "p33FJ32GS610.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32MC101
.include "p33FJ32MC101.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32MC102
.include "p33FJ32MC102.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32MC104
.include "p33FJ32MC104.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32MC202
.include "p33FJ32MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32MC204
.include "p33FJ32MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32MC302
.include "p33FJ32MC302.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ32MC304
.include "p33FJ32MC304.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP202
.include "p33FJ64GP202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP204
.include "p33FJ64GP204.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP206
.include "p33FJ64GP206.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP206A
.include "p33FJ64GP206A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP306
.include "p33FJ64GP306.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP306A
.include "p33FJ64GP306A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP310
.include "p33FJ64GP310.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP310A
.include "p33FJ64GP310A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP706
.include "p33FJ64GP706.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP706A
.include "p33FJ64GP706A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP708
.include "p33FJ64GP708.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP708A
.include "p33FJ64GP708A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP710
.include "p33FJ64GP710.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP710A
.include "p33FJ64GP710A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP802
.include "p33FJ64GP802.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GP804
.include "p33FJ64GP804.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GS406
.include "p33FJ64GS406.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GS606
.include "p33FJ64GS606.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GS608
.include "p33FJ64GS608.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64GS610
.include "p33FJ64GS610.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC202
.include "p33FJ64MC202.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC204
.include "p33FJ64MC204.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC506
.include "p33FJ64MC506.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC506A
.include "p33FJ64MC506A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC508
.include "p33FJ64MC508.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC508A
.include "p33FJ64MC508A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC510
.include "p33FJ64MC510.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC510A
.include "p33FJ64MC510A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC706
.include "p33FJ64MC706.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC706A
.include "p33FJ64MC706A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC710
.include "p33FJ64MC710.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC710A
.include "p33FJ64MC710A.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC802
.include "p33FJ64MC802.inc"
.equ VALID_ID,1
.endif

.ifdef __33FJ64MC804
.include "p33FJ64MC804.inc"
.equ VALID_ID,1
.endif

.ifndef VALID_ID
.error "processor ID not specified in generic include file"
.endif
